### ISSUE TITLE
Use @Inject for injecting ioc stuff into facets

### ISSUE THREAD

**Issue by vankeisb** [pojosontheweb/woko#225]
Would be better than to call woko.ioc.getComponent() all the time...

**Comment by imclem** [comment]
+1

**Comment by vankeisb** [comment]
We already have `woko.ioc.WokoInject` that works on "setter methods". We just need to make it work on fields, so that instead of :

```
@FacetKey(name="foo", profileId="all")
class FooAll extends BaseResolutionFacet {

    private MailService mailService

    @WokoInject(MailService.KEY)
    void injectMs(MailService ms) {
        mailService = ms
    }

    @Override
    Resolution getResolution(ActionBeanContext abc) {
        new StreamingResolution('text/plain', "mail=$mailService")
    }
}
```

one can also write :

```
@FacetKey(name="foo", profileId="all")
class FooAll extends BaseResolutionFacet {

    @WokoInject(MailService.KEY)
    MailService mailService

    @Override
    Resolution getResolution(ActionBeanContext abc) {
        new StreamingResolution('text/plain', "mail=$mailService")
    }
    
}
```

Note that this opens up the `mailService` to binding, but you should use `@StrictBinding` everywhere anyway so...

**Comment by vankeisb** [comment]
We may also want to leave the value blank, and let the Types be used, if possible.

**Comment by vankeisb** [comment]
Requires a new method in `woko.ioc.WokoIocContainer` I think. One that allows to get the list of all registered components.
