### ISSUE TITLE
void

### ISSUE THREAD

**Issue by ghost** [pojosontheweb/woko#235]

**Comment by vankeisb** [comment]
I cannot reproduce on OSX. I need to test on windows.

**Comment by lazaridis-com** [comment]
It seems that the CTRL-C signal does not reach the executed command (`mvn jetty:run-exploded`), but instead simply the `woko.bat`.

**Comment by vankeisb** [comment]
Ok managed to get a Windows VM up and running and I do reproduce : CTRL-C leaves a zombie java process and jetty isn't stopped.

I do not use windows, and I have no idea why this happens.

@imclem any idea ?

As a side note, we rarely use `woko start`, excepted for demos. We usually start the app from an IDE, or drop it into an app server.

**Comment by lazaridis-com** [comment]
(The side-note doesn't matter. `woko start` exists, and that's very nice, especially for newcomers). 

I've described the most possible cause of this: the CTRL-C signal is most possibly catched by the `woko.bat`

A starting point for a solution:

http://superuser.com/questions/35698/how-to-supress-terminate-batch-job-y-n-confirmation

**Comment by vankeisb** [comment]
Yep `woko.bat` forks another process (mvn ...), and this one never gets killed on CTRL-C.

You can use `woko stop` from another console window as a workaround until this bug gets fixed.

**Comment by vankeisb** [comment]
Neh, `woko stop` seems to do nothing...

**Comment by lazaridis-com** [comment]
The workaround is to use `mvn jetty:run`
